name: app-name-kebab-case

services:
  backend:
    build:
      context: ../../
      dockerfile: deploy/dev/backend/Dockerfile
      tags:
        - "app-name-kebab-case-backend:dev"
    container_name: app-name-kebab-case-backend
    volumes:
      - ../..:/app
      - backend-data:/run/app
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      JWT_SECRET: super-secret-jwt-secret
      POSTGRES_URL: postgresql+psycopg://root:root@postgres/root
    command: app-name-kebab-case-dev
    healthcheck:
      test: python3 -c "from urllib.request import urlopen as f; assert f('http://backend:8000/health').status == 204"
      start_period: 2m
      start_interval: 0.5s
      interval: 10s

  postgres:
    image: postgres:16.3-alpine3.19
    container_name: app-name-kebab-case-postgres
    labels:
      deployment: dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    healthcheck:
      test: pg_isready -d root -U root
      start_period: 1m
      start_interval: 1s
      interval: 5s

volumes:
  backend-data: null

  postgres-data:
    labels:
      db: true
