"""
deffer `players_current_game_id_fkey`.

Revision ID: 022844f6b4d2
Revises: 3d096a9eb585
Create Date: 2025-06-22 13:57:43.872209

"""

from collections.abc import Sequence

from alembic import op


revision: str = "022844f6b4d2"
down_revision: str | None = "3d096a9eb585"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("players_current_game_id_fkey"), "players", type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "players",
        "games",
        ["game_location_game_id"],
        ["id"],
        initially="DEFERRED",
        deferrable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "players_current_game_id_fkey", "players", type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("players_current_game_id_fkey"),
        "players",
        "games",
        ["game_location_game_id"],
        ["id"],
    )
    # ### end Alembic commands ###
