"""
use `admin_right` instead of `role`s.

Revision ID: 08f3884d27ff
Revises: 974e328b8043
Create Date: 2025-09-05 17:18:21.659565

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


revision: str = "08f3884d27ff"
down_revision: str | None = "974e328b8043"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("via_admin_token", "via_other_admin", name="admin_right").create(
        op.get_bind(),
    )
    op.add_column(
        "users",
        sa.Column(
            "admin_right",
            postgresql.ENUM(
                "via_admin_token",
                "via_other_admin",
                name="admin_right",
                create_type=False,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "admin_right_via_other_admin_admin_id",
            sa.BigInteger(),
            nullable=True,
        ),
    )
    op.drop_index(
        op.f("ix_users_role_not_root_admin_root_admin_id"),
        table_name="users",
        postgresql_where="(role_not_root_admin_root_admin_id IS NOT NULL)",
    )
    op.create_index(
        "ix_users_admin_right",
        "users",
        ["admin_right"],
        unique=False,
        postgresql_where=sa.text("admin_right IS NOT NULL"),
    )
    op.create_index(
        "ix_users_admin_right_via_other_admin_admin_id",
        "users",
        ["admin_right_via_other_admin_admin_id"],
        unique=False,
        postgresql_where=sa.text(
            "admin_right_via_other_admin_admin_id IS NOT NULL",
        ),
    )
    op.drop_constraint(
        op.f("users_role_not_root_admin_root_admin_id_fkey"),
        "users",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "users_admin_right_via_other_admin_admin_id_fkey",
        "users",
        "users",
        ["admin_right_via_other_admin_admin_id"],
        ["id"],
        initially="DEFERRED",
        deferrable=True,
    )
    op.drop_column("users", "role_not_root_admin_root_admin_id")
    op.drop_column("users", "role")
    sa.Enum(
        "root_admin",
        "not_root_admin",
        "regular_user",
        name="user_role",
    ).drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "root_admin",
        "not_root_admin",
        "regular_user",
        name="user_role",
    ).create(op.get_bind())
    op.add_column(
        "users",
        sa.Column(
            "role",
            postgresql.ENUM(
                "root_admin",
                "not_root_admin",
                "regular_user",
                name="user_role",
                create_type=False,
            ),
            server_default=sa.text("'regular_user'::user_role"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "role_not_root_admin_root_admin_id",
            sa.BIGINT(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(
        "users_admin_right_via_other_admin_admin_id_fkey",
        "users",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("users_role_not_root_admin_root_admin_id_fkey"),
        "users",
        "users",
        ["role_not_root_admin_root_admin_id"],
        ["id"],
        initially="DEFERRED",
        deferrable=True,
    )
    op.drop_index(
        "ix_users_admin_right_via_other_admin_admin_id",
        table_name="users",
        postgresql_where=sa.text(
            "admin_right_via_other_admin_admin_id IS NOT NULL",
        ),
    )
    op.drop_index(
        "ix_users_admin_right",
        table_name="users",
        postgresql_where=sa.text("admin_right IS NOT NULL"),
    )
    op.create_index(
        op.f("ix_users_role_not_root_admin_root_admin_id"),
        "users",
        ["role_not_root_admin_root_admin_id"],
        unique=False,
        postgresql_where="(role_not_root_admin_root_admin_id IS NOT NULL)",
    )
    op.drop_column("users", "admin_right_via_other_admin_admin_id")
    op.drop_column("users", "admin_right")
    sa.Enum("via_admin_token", "via_other_admin", name="admin_right").drop(
        op.get_bind(),
    )
    # ### end Alembic commands ###
