"""
fix `players.id` fk data types.

Revision ID: 1106a6a301dc
Revises: 022844f6b4d2
Create Date: 2025-06-22 14:03:44.506811

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "1106a6a301dc"
down_revision: str | None = "022844f6b4d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "players",
        "game_location_chat_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "players",
        "game_location_chat_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
