"""
add `last_games`.

Revision ID: 12531d2d5b0f
Revises: 584168970f91
Create Date: 2025-07-25 15:17:13.594879

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "12531d2d5b0f"
down_revision: str | None = "584168970f91"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "last_games",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("game_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"], ["games.id"], initially="DEFERRED", deferrable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], initially="DEFERRED", deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("last_games")
    # ### end Alembic commands ###
