"""
add emoji columns to `games`.

Revision ID: 14ac685f156c
Revises: eccc8a23a9ce
Create Date: 2025-06-21 03:24:22.371583

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "14ac685f156c"
down_revision: str | None = "eccc8a23a9ce"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "games",
        sa.Column(
            "player1_emoji_char",
            sa.String(),
            server_default="❌",
            nullable=False,
        ),
    )
    op.add_column(
        "games",
        sa.Column(
            "player2_emoji_char",
            sa.String(),
            server_default="⭕️",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "player2_emoji_char")
    op.drop_column("games", "player1_emoji_char")
    # ### end Alembic commands ###
