"""
add player -> game fk.

Revision ID: 210a9f8ec6c9
Revises: f7293bb0810e
Create Date: 2025-06-18 09:49:18.179326

"""

from collections.abc import Sequence

from alembic import op


revision: str = "210a9f8ec6c9"
down_revision: str | None = "f7293bb0810e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "players", "games", ["current_game_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "players", type_="foreignkey")
    # ### end Alembic commands ###
