"""
add `ix_invitations_to_game_invitation_datetime`.

Revision ID: 325e2d4a600b
Revises: 5fd844c21a61
Create Date: 2025-09-12 06:02:02.399393

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "325e2d4a600b"
down_revision: str | None = "5fd844c21a61"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_invitations_to_game_invitation_datetime",
        "invitations_to_game",
        ["invitation_datetime"],
        unique=False,
        postgresql_where=sa.text("state = 'active'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_invitations_to_game_invitation_datetime",
        table_name="invitations_to_game",
        postgresql_where=sa.text("state = 'active'"),
    )
    # ### end Alembic commands ###
