"""
rename `ix_user_emojis_player_id`.

Revision ID: 333ad9363bd2
Revises: 5e475271bf44
Create Date: 2025-07-18 12:30:03.816916

"""

from collections.abc import Sequence

from alembic import op


revision: str = "333ad9363bd2"
down_revision: str | None = "5e475271bf44"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_player_emojis_player_id"), table_name="user_emojis")
    op.create_index(
        op.f("ix_user_emojis_player_id"),
        "user_emojis",
        ["player_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_emojis_player_id"), table_name="user_emojis")
    op.create_index(
        op.f("ix_player_emojis_player_id"),
        "user_emojis",
        ["player_id"],
        unique=False,
    )
    # ### end Alembic commands ###
