"""
index and defer all fks.

Revision ID: 3a1d48a54125
Revises: e8f293cdc7bd
Create Date: 2025-06-28 08:42:46.903102

"""

from collections.abc import Sequence

from alembic import op


revision: str = "3a1d48a54125"
down_revision: str | None = "e8f293cdc7bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_cells_filler_id"), "cells", ["filler_id"], unique=False,
    )
    op.create_index(
        op.f("ix_cells_game_id"), "cells", ["game_id"], unique=False,
    )
    op.drop_constraint(
        op.f("cells_filler_id_fkey"), "cells", type_="foreignkey",
    )
    op.drop_constraint(op.f("cells_game_id_fkey"), "cells", type_="foreignkey")
    op.create_foreign_key(
        "cells_filler_id_fkey",
        "cells",
        "players",
        ["filler_id"],
        ["id"],
        initially="DEFERRED",
        deferrable=True,
    )
    op.create_foreign_key(
        "cells_game_id_fkey",
        "cells",
        "games",
        ["game_id"],
        ["id"],
        initially="DEFERRED",
        deferrable=True,
    )
    op.create_index(
        op.f("ix_game_results_canceler_id"),
        "game_results",
        ["canceler_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_game_results_win_winner_id"),
        "game_results",
        ["win_winner_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("game_results_canceler_id_fkey"),
        "game_results",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("game_results_winner_id_fkey"), "game_results", type_="foreignkey",
    )
    op.drop_constraint(
        op.f("game_results_game_id_fkey"), "game_results", type_="foreignkey",
    )
    op.create_foreign_key(
        "game_results_game_id_fkey",
        "game_results",
        "games",
        ["game_id"],
        ["id"],
        initially="DEFERRED",
        deferrable=True,
    )
    op.create_foreign_key(
        "game_results_canceler_id_fkey",
        "game_results",
        "players",
        ["canceler_id"],
        ["id"],
        initially="DEFERRED",
        deferrable=True,
    )
    op.create_foreign_key(
        "game_results_winner_id_fkey",
        "game_results",
        "players",
        ["win_winner_id"],
        ["id"],
        initially="DEFERRED",
        deferrable=True,
    )
    op.create_index(
        op.f("ix_games_player1_id"), "games", ["player1_id"], unique=False,
    )
    op.create_index(
        op.f("ix_games_player2_id"), "games", ["player2_id"], unique=False,
    )
    op.drop_constraint(
        op.f("games_player1_id_fkey"), "games", type_="foreignkey",
    )
    op.drop_constraint(
        op.f("games_player2_id_fkey"), "games", type_="foreignkey",
    )
    op.create_foreign_key(
        "games_player1_id_fkey",
        "games",
        "players",
        ["player2_id"],
        ["id"],
        initially="DEFERRED",
        deferrable=True,
    )
    op.create_foreign_key(
        "games_player2_id_fkey",
        "games",
        "players",
        ["player1_id"],
        ["id"],
        initially="DEFERRED",
        deferrable=True,
    )
    op.create_index(
        op.f("ix_player_emojis_player_id"),
        "player_emojis",
        ["player_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("player_emojis_player_id_fkey"),
        "player_emojis",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "player_emojis_player_id_fkey",
        "player_emojis",
        "players",
        ["player_id"],
        ["id"],
        initially="DEFERRED",
        deferrable=True,
    )
    op.create_index(
        op.f("ix_players_game_location_game_id"),
        "players",
        ["game_location_game_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_players_selected_emoji_id"),
        "players",
        ["selected_emoji_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stars_purchases_player_id"),
        "stars_purchases",
        ["player_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("stars_purchases_player_id_fkey"),
        "stars_purchases",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "stars_purchases_player_id_fkey",
        "stars_purchases",
        "players",
        ["player_id"],
        ["id"],
        initially="DEFERRED",
        deferrable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "stars_purchases_player_id_fkey", "stars_purchases", type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("stars_purchases_player_id_fkey"),
        "stars_purchases",
        "players",
        ["player_id"],
        ["id"],
    )
    op.drop_index(
        op.f("ix_stars_purchases_player_id"), table_name="stars_purchases",
    )
    op.drop_index(op.f("ix_players_selected_emoji_id"), table_name="players")
    op.drop_index(
        op.f("ix_players_game_location_game_id"), table_name="players",
    )
    op.drop_constraint(
        "player_emojis_player_id_fkey", "player_emojis", type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("player_emojis_player_id_fkey"),
        "player_emojis",
        "players",
        ["player_id"],
        ["id"],
    )
    op.drop_index(
        op.f("ix_player_emojis_player_id"), table_name="player_emojis",
    )
    op.drop_constraint("games_player2_id_fkey", "games", type_="foreignkey")
    op.drop_constraint("games_player1_id_fkey", "games", type_="foreignkey")
    op.create_foreign_key(
        op.f("games_player2_id_fkey"),
        "games",
        "players",
        ["player2_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("games_player1_id_fkey"),
        "games",
        "players",
        ["player1_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_games_player2_id"), table_name="games")
    op.drop_index(op.f("ix_games_player1_id"), table_name="games")
    op.drop_constraint(
        "game_results_game_id_fkey", "game_results", type_="foreignkey",
    )
    op.drop_constraint(
        "game_results_winner_id_fkey", "game_results", type_="foreignkey",
    )
    op.drop_constraint(
        "game_results_canceler_id_fkey", "game_results", type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("game_results_game_id_fkey"),
        "game_results",
        "games",
        ["game_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("game_results_winner_id_fkey"),
        "game_results",
        "players",
        ["win_winner_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("game_results_canceler_id_fkey"),
        "game_results",
        "players",
        ["canceler_id"],
        ["id"],
    )
    op.drop_index(
        op.f("ix_game_results_win_winner_id"), table_name="game_results",
    )
    op.drop_index(
        op.f("ix_game_results_canceler_id"), table_name="game_results",
    )
    op.drop_constraint("cells_game_id_fkey", "cells", type_="foreignkey")
    op.drop_constraint("cells_filler_id_fkey", "cells", type_="foreignkey")
    op.create_foreign_key(
        op.f("cells_game_id_fkey"), "cells", "games", ["game_id"], ["id"],
    )
    op.create_foreign_key(
        op.f("cells_filler_id_fkey"), "cells", "players", ["filler_id"], ["id"],
    )
    op.drop_index(op.f("ix_cells_game_id"), table_name="cells")
    op.drop_index(op.f("ix_cells_filler_id"), table_name="cells")
    # ### end Alembic commands ###
