"""
make `selected_emoji_id` deferred.

Revision ID: 43336a39f1e2
Revises: 55f7ecc0f5a4
Create Date: 2025-06-27 09:04:30.539970

"""

from collections.abc import Sequence

from alembic import op


revision: str = "43336a39f1e2"
down_revision: str | None = "55f7ecc0f5a4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("players_selected_emoji_id_fkey"), "players", type_="foreignkey",
    )
    op.create_foreign_key(
        "players_selected_emoji_id_fkey",
        "players",
        "player_emojis",
        ["selected_emoji_id"],
        ["id"],
        initially="DEFERRED",
        deferrable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "players_selected_emoji_id_fkey", "players", type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("players_selected_emoji_id_fkey"),
        "players",
        "player_emojis",
        ["selected_emoji_id"],
        ["id"],
    )
    # ### end Alembic commands ###
