"""
add `player_emojis` table.

Revision ID: 55f7ecc0f5a4
Revises: 59f959c8e3cd
Create Date: 2025-06-25 16:45:03.256279

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "55f7ecc0f5a4"
down_revision: str | None = "59f959c8e3cd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player_emojis",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.BigInteger(), nullable=False),
        sa.Column("emoji_str", sa.CHAR(length=1), nullable=False),
        sa.Column("datetime_of_purchase", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "players",
        sa.Column("selected_emoji_id", sa.Uuid(), nullable=True),
    )
    op.create_foreign_key(
        "players_selected_emoji_id_fkey",
        "players",
        "player_emojis",
        ["selected_emoji_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "players_selected_emoji_id_fkey", "players", type_="foreignkey",
    )
    op.drop_column("players", "selected_emoji_id")
    op.drop_table("player_emojis")
    # ### end Alembic commands ###
