"""
add game cancelation.

Revision ID: 59f959c8e3cd
Revises: 54be98063760
Create Date: 2025-06-25 10:55:35.024804

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


revision: str = "59f959c8e3cd"
down_revision: str | None = "54be98063760"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("completed", "cancelled", name="game_result_type").create(
        op.get_bind(),
    )
    op.add_column(
        "game_results",
        sa.Column(
            "type",
            postgresql.ENUM(
                "completed",
                "cancelled",
                name="game_result_type",
                create_type=False,
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "game_results",
        sa.Column("canceler_id", sa.BigInteger(), nullable=True),
    )
    op.create_foreign_key(
        "game_results_canceler_id_fkey",
        "game_results",
        "players",
        ["canceler_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "game_results_canceler_id_fkey",
        "game_results",
        type_="foreignkey",
    )
    op.drop_column("game_results", "canceler_id")
    op.drop_column("game_results", "type")
    sa.Enum("completed", "cancelled", name="game_result_type").drop(
        op.get_bind(),
    )
    # ### end Alembic commands ###
