"""
add `matchmaking_queue_user_waitings`.

Revision ID: 5ba4cd32c047
Revises: 982aa776c214
Create Date: 2025-08-28 11:06:51.152485

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "5ba4cd32c047"
down_revision: str | None = "982aa776c214"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "matchmaking_queue_user_waitings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("start_datetime", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], initially="DEFERRED", deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_matchmaking_queue_user_waitings_user_id"),
        "matchmaking_queue_user_waitings",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_matchmaking_queue_user_waitings_user_id"),
        table_name="matchmaking_queue_user_waitings",
    )
    op.drop_table("matchmaking_queue_user_waitings")
    # ### end Alembic commands ###
