"""
add `ai` table.

Revision ID: 5e475271bf44
Revises: 90038668685f
Create Date: 2025-07-18 12:27:15.123203

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


revision: str = "5e475271bf44"
down_revision: str | None = "90038668685f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("gemini_2_0_flash", name="ai_type").create(op.get_bind())
    op.create_table(
        "ais",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(
                "gemini_2_0_flash", name="ai_type", create_type=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ais")
    sa.Enum("gemini_2_0_flash", name="ai_type").drop(op.get_bind())
    # ### end Alembic commands ###
