"""
add `invitations_to_game`.

Revision ID: 5fd844c21a61
Revises: 08f3884d27ff
Create Date: 2025-09-11 08:39:12.127082

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


revision: str = "5fd844c21a61"
down_revision: str | None = "08f3884d27ff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "active",
        "auto_cancelled",
        "cancelled_by_user",
        "rejected",
        "accepted",
        name="invitation_to_game_state",
    ).create(op.get_bind())
    op.create_table(
        "invitations_to_game",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("inviting_user_id", sa.BigInteger(), nullable=False),
        sa.Column("invited_user_id", sa.BigInteger(), nullable=False),
        sa.Column("invitation_datetime", sa.DateTime(), nullable=False),
        sa.Column(
            "state",
            postgresql.ENUM(
                "active",
                "auto_cancelled",
                "cancelled_by_user",
                "rejected",
                "accepted",
                name="invitation_to_game_state",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["invited_user_id"],
            ["users.id"],
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.ForeignKeyConstraint(
            ["inviting_user_id"],
            ["users.id"],
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_invitations_to_game_invited_user_id"),
        "invitations_to_game",
        ["invited_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_invitations_to_game_inviting_user_id"),
        "invitations_to_game",
        ["inviting_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_invitations_to_game_user_ids",
        "invitations_to_game",
        ["inviting_user_id", "invited_user_id"],
        unique=True,
        postgresql_where=sa.text("state = 'active'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_invitations_to_game_user_ids",
        table_name="invitations_to_game",
        postgresql_where=sa.text("state = 'active'"),
    )
    op.drop_index(
        op.f("ix_invitations_to_game_inviting_user_id"),
        table_name="invitations_to_game",
    )
    op.drop_index(
        op.f("ix_invitations_to_game_invited_user_id"),
        table_name="invitations_to_game",
    )
    op.drop_table("invitations_to_game")
    sa.Enum(
        "active",
        "auto_cancelled",
        "cancelled_by_user",
        "rejected",
        "accepted",
        name="invitation_to_game_state",
    ).drop(op.get_bind())
    # ### end Alembic commands ###
