"""
index `users.rating`.

Revision ID: 6642791b3bf8
Revises: 7ce97d6efd2c
Create Date: 2025-09-20 08:16:00.242481

"""

from collections.abc import Sequence

from alembic import op


revision: str = "6642791b3bf8"
down_revision: str | None = "7ce97d6efd2c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_users_rating"), "users", ["rating"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_rating"), table_name="users")
    # ### end Alembic commands ###
