"""
remove aggregation data from `users`.

Revision ID: 679c935495d1
Revises: dc59db88676c
Create Date: 2025-09-16 04:42:25.995128

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "679c935495d1"
down_revision: str | None = "dc59db88676c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "number_of_draws")
    op.drop_column("users", "number_of_wins")
    op.drop_column("users", "number_of_defeats")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "number_of_defeats",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "number_of_wins",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "number_of_draws",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
