"""
add `role` to `users`.

Revision ID: 6eddb11b02fa
Revises: f969a41d60f0
Create Date: 2025-08-21 12:36:24.446161

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


revision: str = "6eddb11b02fa"
down_revision: str | None = "f969a41d60f0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("admin", "regular_user", name="user_role").create(op.get_bind())
    op.add_column(
        "users",
        sa.Column(
            "role",
            postgresql.ENUM(
                "admin", "regular_user", name="user_role", create_type=False,
            ),
            server_default="regular_user",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    sa.Enum("admin", "regular_user", name="user_role").drop(op.get_bind())
    # ### end Alembic commands ###
