"""
add not root admins.

Revision ID: 974e328b8043
Revises: 5ba4cd32c047
Create Date: 2025-09-03 17:20:36.803926

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference


revision: str = "974e328b8043"
down_revision: str | None = "5ba4cd32c047"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "role_not_root_admin_root_admin_id",
            sa.BigInteger(),
            nullable=True,
        ),
    )
    op.create_index(
        "ix_users_role_not_root_admin_root_admin_id",
        "users",
        ["role_not_root_admin_root_admin_id"],
        unique=False,
        postgresql_where=sa.text(
            "role_not_root_admin_root_admin_id IS NOT NULL",
        ),
    )
    op.create_foreign_key(
        "users_role_not_root_admin_root_admin_id_fkey",
        "users",
        "users",
        ["role_not_root_admin_root_admin_id"],
        ["id"],
        initially="DEFERRED",
        deferrable=True,
    )
    op.sync_enum_values(  # type: ignore[attr-defined]
        enum_schema="public",
        enum_name="user_role",
        new_values=["root_admin", "not_root_admin", "regular_user"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="users",
                column_name="role",
                existing_server_default="'regular_user'::user_role",
            ),
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # type: ignore[attr-defined]
        enum_schema="public",
        enum_name="user_role",
        new_values=["root_admin", "regular_user"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="users",
                column_name="role",
                existing_server_default="'regular_user'::user_role",
            ),
        ],
        enum_values_to_rename=[],
    )
    op.drop_constraint(
        "users_role_not_root_admin_root_admin_id_fkey",
        "users",
        type_="foreignkey",
    )
    op.drop_index(
        "ix_users_role_not_root_admin_root_admin_id",
        table_name="users",
        postgresql_where=sa.text(
            "role_not_root_admin_root_admin_id IS NOT NULL",
        ),
    )
    op.drop_column("users", "role_not_root_admin_root_admin_id")
    # ### end Alembic commands ###
