"""
rename `user_role.admin` to `user_role.root_admin`.

Revision ID: 982aa776c214
Revises: 6eddb11b02fa
Create Date: 2025-08-21 14:13:30.942175

"""

from collections.abc import Sequence

from alembic import op
from alembic_postgresql_enum import TableReference


revision: str = "982aa776c214"
down_revision: str | None = "6eddb11b02fa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # type: ignore[attr-defined]
        enum_schema="public",
        enum_name="user_role",
        new_values=["root_admin", "regular_user"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="users",
                column_name="role",
                existing_server_default="'regular_user'::user_role",
            ),
        ],
        enum_values_to_rename=[("admin", "root_admin")],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # type: ignore[attr-defined]
        enum_schema="public",
        enum_name="user_role",
        new_values=["admin", "regular_user"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="users",
                column_name="role",
                existing_server_default="'regular_user'::user_role",
            ),
        ],
        enum_values_to_rename=[("root_admin", "admin")],
    )
    # ### end Alembic commands ###
