"""
add `game_location_chat_id` to `players`.

Revision ID: 9b894c046d5e
Revises: 210a9f8ec6c9
Create Date: 2025-06-19 09:29:08.976222

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "9b894c046d5e"
down_revision: str | None = "210a9f8ec6c9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "players",
        sa.Column("game_location_chat_id", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("players", "game_location_chat_id")
    # ### end Alembic commands ###
