"""
create tables for `StarsPurchase`.

Revision ID: b19b4f555d6d
Revises: ac61cf032bda
Create Date: 2025-06-28 18:44:18.600716

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "b19b4f555d6d"
down_revision: str | None = "ac61cf032bda"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("paid_rubles_total_kopecks", sa.BigInteger(), nullable=False),
        sa.Column("start_datetime", sa.DateTime(), nullable=False),
        sa.Column("completion_datetime", sa.DateTime(), nullable=True),
        sa.Column("success_id", sa.String(), nullable=True),
        sa.Column("success_gateway_id", sa.String(), nullable=True),
        sa.Column("is_cancelled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stars_purchases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("location_player_id", sa.BigInteger(), nullable=False),
        sa.Column("location_chat_id", sa.BigInteger(), nullable=False),
        sa.Column("new_stars", sa.Integer(), nullable=False),
        sa.Column("payment_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["location_player_id"],
            ["players.id"],
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stars_purchases_location_player_id"),
        "stars_purchases",
        ["location_player_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stars_purchases_payment_id"),
        "stars_purchases",
        ["payment_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_stars_purchases_payment_id"), table_name="stars_purchases",
    )
    op.drop_index(
        op.f("ix_stars_purchases_location_player_id"),
        table_name="stars_purchases",
    )
    op.drop_table("stars_purchases")
    op.drop_table("payments")
    # ### end Alembic commands ###
