"""
add `cells.ai_filler_id`.

Revision ID: b63576e3d5f5
Revises: 333ad9363bd2
Create Date: 2025-07-18 12:32:45.870453

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "b63576e3d5f5"
down_revision: str | None = "333ad9363bd2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cells", sa.Column("ai_filler_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_cells_ai_filler_id"), "cells", ["ai_filler_id"], unique=False,
    )
    op.create_foreign_key(
        None,
        "cells",
        "ais",
        ["ai_filler_id"],
        ["id"],
        initially="DEFERRED",
        deferrable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("cells_ai_filler_id_fkey", "cells", type_="foreignkey")
    op.drop_index(op.f("ix_cells_ai_filler_id"), table_name="cells")
    op.drop_column("cells", "ai_filler_id")
    # ### end Alembic commands ###
