"""
merge `matchmaking_user_waitings` and `users`.

Revision ID: ba0f7132baef
Revises: 051831b12f05
Create Date: 2025-09-17 17:37:58.210228

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


revision: str = "ba0f7132baef"
down_revision: str | None = "051831b12f05"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_matchmaking_user_waitings_user_id"),
        table_name="matchmaking_user_waitings",
    )
    op.drop_table("matchmaking_user_waitings")
    op.add_column(
        "users",
        sa.Column(
            "has_matchmaking_waiting",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "matchmaking_waiting_start_datetime", sa.DateTime(), nullable=True,
        ),
    )
    op.create_index(
        "ix_users_has_matchmaking_waiting",
        "users",
        ["has_matchmaking_waiting"],
        unique=False,
        postgresql_where=sa.text("has_matchmaking_waiting IS true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_users_has_matchmaking_waiting",
        table_name="users",
        postgresql_where=sa.text("has_matchmaking_waiting IS true"),
    )
    op.drop_column("users", "matchmaking_waiting_start_datetime")
    op.drop_column("users", "has_matchmaking_waiting")
    op.create_table(
        "matchmaking_user_waitings",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "start_datetime",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("matchmaking_user_waitings_user_id_fkey"),
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("matchmaking_user_waitings_pkey"),
        ),
    )
    op.create_index(
        op.f("ix_matchmaking_user_waitings_user_id"),
        "matchmaking_user_waitings",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###
