"""
exclude nulls from `ix_stars_purchases_payment_id`.

Revision ID: ce3ee64d0d3b
Revises: 86d75da6c607
Create Date: 2025-07-02 05:19:22.411169

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "ce3ee64d0d3b"
down_revision: str | None = "86d75da6c607"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_stars_purchases_payment_id"), table_name="stars_purchases",
    )
    op.create_index(
        op.f("ix_stars_purchases_payment_id"),
        "stars_purchases",
        ["payment_id"],
        unique=False,
        postgresql_where=sa.text("payment_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_stars_purchases_payment_id"), table_name="stars_purchases",
    )
    op.create_index(
        op.f("ix_stars_purchases_payment_id"),
        "stars_purchases",
        ["payment_id"],
        unique=False,
    )
    # ### end Alembic commands ###
