"""
add `username` columns to `invitations_to_game`.

Revision ID: dc1b9f720a1d
Revises: 2dcb2be9e277
Create Date: 2025-10-05 09:44:49.062023

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "dc1b9f720a1d"
down_revision: str | None = "2dcb2be9e277"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invitations_to_game",
        sa.Column("inviting_user_username", sa.String(), nullable=True),
    )
    op.add_column(
        "invitations_to_game",
        sa.Column("invited_user_username", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invitations_to_game", "invited_user_username")
    op.drop_column("invitations_to_game", "inviting_user_username")
    # ### end Alembic commands ###
