"""
remove `last_games`.

Revision ID: dc59db88676c
Revises: 325e2d4a600b
Create Date: 2025-09-15 10:38:01.081651

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "dc59db88676c"
down_revision: str | None = "325e2d4a600b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("last_games")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "last_games",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("game_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
            name=op.f("last_games_game_id_fkey"),
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("last_games_user_id_fkey"),
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("last_games_pkey")),
    )
    # ### end Alembic commands ###
