"""
join `games` and `ais`.

Revision ID: e05971d2b8d5
Revises: 2964228ec4df
Create Date: 2025-07-18 12:51:21.203090

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "e05971d2b8d5"
down_revision: str | None = "2964228ec4df"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("games", sa.Column("ai1_id", sa.Uuid(), nullable=True))
    op.add_column("games", sa.Column("ai2_id", sa.Uuid(), nullable=True))
    op.alter_column(
        "games", "player1_id", existing_type=sa.BIGINT(), nullable=True,
    )
    op.alter_column(
        "games", "player2_id", existing_type=sa.BIGINT(), nullable=True,
    )
    op.create_index(op.f("ix_games_ai1_id"), "games", ["ai1_id"], unique=False)
    op.create_index(op.f("ix_games_ai2_id"), "games", ["ai2_id"], unique=False)
    op.create_foreign_key(
        None,
        "games",
        "ais",
        ["ai2_id"],
        ["id"],
        initially="DEFERRED",
        deferrable=True,
    )
    op.create_foreign_key(
        None,
        "games",
        "ais",
        ["ai1_id"],
        ["id"],
        initially="DEFERRED",
        deferrable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("games_ai1_id_fkey", "games", type_="foreignkey")
    op.drop_constraint("games_ai2_id_fkey", "games", type_="foreignkey")
    op.drop_index(op.f("ix_games_ai2_id"), table_name="games")
    op.drop_index(op.f("ix_games_ai1_id"), table_name="games")
    op.alter_column(
        "games", "player2_id", existing_type=sa.BIGINT(), nullable=False,
    )
    op.alter_column(
        "games", "player1_id", existing_type=sa.BIGINT(), nullable=False,
    )
    op.drop_column("games", "ai2_id")
    op.drop_column("games", "ai1_id")
    # ### end Alembic commands ###
