"""
add user table.

Revision ID: e78dd190868f
Revises:
Create Date: 2025-03-30 13:37:27.048793

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "e78dd190868f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("users",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("name"),
    sa.UniqueConstraint("name", name="users_name_unique"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
