"""
add `stars_purchases` table.

Revision ID: e8f293cdc7bd
Revises: 43336a39f1e2
Create Date: 2025-06-28 08:35:17.246818

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "e8f293cdc7bd"
down_revision: str | None = "43336a39f1e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stars_purchases",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("payment_gateway_id", sa.String(), nullable=False),
        sa.Column("player_id", sa.BigInteger(), nullable=False),
        sa.Column("stars", sa.Integer(), nullable=False),
        sa.Column("kopecks", sa.Integer(), nullable=False),
        sa.Column("datetime_", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"]),
        sa.PrimaryKeyConstraint("id", "payment_gateway_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stars_purchases")
    # ### end Alembic commands ###
