"""
add `players.account_stars`.

Revision ID: fa2086ce276b
Revises: 62217b947df9
Create Date: 2025-06-23 03:27:56.249742

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "fa2086ce276b"
down_revision: str | None = "62217b947df9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "players",
        sa.Column(
            "account_stars",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("players", "account_stars")
    # ### end Alembic commands ###
