name: CD

on:
  release:
    branches: [prod]
    types: [published]

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64, prod]
    environment: Production
    steps:
      - uses: actions/checkout@v4

      - name: add secrets
        run: |
          echo "bot_token: ${{ secrets.BOT_TOKEN }}" > deploy/prod/ttt/secrets.yaml
          echo "payments_token: ${{ secrets.PAYMENTS_TOKEN }}" >> deploy/prod/ttt/secrets.yaml
          echo "gemini_api_key: ${{ secrets.GEMINI_API_KEY }}" >> deploy/prod/ttt/secrets.yaml
          echo "sentry_dsn: ${{ secrets.SENTRY_DSN }}" >> deploy/prod/ttt/secrets.yaml

      - name: deploy
        run: bash ./deploy/prod/deploy.sh
        env:
            REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}

            POSTGRES_TTT_PASSWORD: ${{ secrets.POSTGRES_TTT_PASSWORD }}
            POSTGRES_REPLICA_PASSWORD: ${{ secrets.POSTGRES_REPLICA_PASSWORD }}

            NATS_TOKEN: ${{ secrets.NATS_TOKEN }}

            GEMINI_URL: ${{ secrets.GEMINI_URL }}

            GRAFANA_ADMIN_PASSWORD: ${{ secrets.GRAFANA_ADMIN_PASSWORD }}
