name: CD

on:
  release:
    branches: [ "main" ]
    type: released

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: deploy
      run: bash ./deploy/prod/deploy.sh
